// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7lUH8mpIJItrYArkHv-Qm40-EK7ldIuE',
    appId: '1:665921199744:web:db67848fb5e50d84f11065',
    messagingSenderId: '665921199744',
    projectId: 'portalsi-web-real',
    authDomain: 'portalsi-web-real.firebaseapp.com',
    storageBucket: 'portalsi-web-real.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA3DDTJDc_xpSOKmkny9Y6Qv7wk3zuTHA',
    appId: '1:665921199744:android:ecee51fe51a91c21f11065',
    messagingSenderId: '665921199744',
    projectId: 'portalsi-web-real',
    storageBucket: 'portalsi-web-real.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB0fAv_P7Jp93w79dRyhEjPib3MQrJ8gs',
    appId: '1:665921199744:ios:cdfc3e9358f05b95f11065',
    messagingSenderId: '665921199744',
    projectId: 'portalsi-web-real',
    storageBucket: 'portalsi-web-real.firebasestorage.app',
    iosBundleId: 'com.example.portalSi',
  );
}
