// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4OX0saL9tpkjAHERBPwURsykdvXRmFhk',
    appId: '1:448077829511:web:d922222f7ed15673bbaf22',
    messagingSenderId: '448077829511',
    projectId: 'portal-si-d6059',
    authDomain: 'portal-si-d6059.firebaseapp.com',
    storageBucket: 'portal-si-d6059.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBodTa_o2TbN36H0_TUVAWW_3m5irKKFvs',
    appId: '1:448077829511:android:e09a313b3224a4efbbaf22',
    messagingSenderId: '448077829511',
    projectId: 'portal-si-d6059',
    storageBucket: 'portal-si-d6059.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYZg4gAiT5eiAcOfyz919ICLzVHekGy4U',
    appId: '1:448077829511:ios:c0862a5d55a15e72bbaf22',
    messagingSenderId: '448077829511',
    projectId: 'portal-si-d6059',
    storageBucket: 'portal-si-d6059.firebasestorage.app',
    iosBundleId: 'com.example.portalSi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYZg4gAiT5eiAcOfyz919ICLzVHekGy4U',
    appId: '1:448077829511:ios:c0862a5d55a15e72bbaf22',
    messagingSenderId: '448077829511',
    projectId: 'portal-si-d6059',
    storageBucket: 'portal-si-d6059.firebasestorage.app',
    iosBundleId: 'com.example.portalSi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4OX0saL9tpkjAHERBPwURsykdvXRmFhk',
    appId: '1:448077829511:web:beb79fa916bbf872bbaf22',
    messagingSenderId: '448077829511',
    projectId: 'portal-si-d6059',
    authDomain: 'portal-si-d6059.firebaseapp.com',
    storageBucket: 'portal-si-d6059.firebasestorage.app',
  );
}
